version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: banking_user
      POSTGRES_PASSWORD: banking_pass
      POSTGRES_DB: banking_demo
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U banking_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: banking-app-api
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://banking_user:banking_pass@db:5432/banking_demo
    volumes:
      - ./app/src:/app/src   # hot reload for dev

volumes:
  postgres_data:
